version: '3.5'

services: 
  app: 
    build:
      context: . 
      dockerfile: _dockerfiles/app/dockerfile
    command: ["python", "./manage.py", "runserver", "0.0.0.0:8000"]
    volumes: 
      - .:/code
    ports: 
      - 8000:8000   
    env_file:
      - _dockerfiles/app/local.env
    depends_on:
      - db

  db: 
    build:
      context: .
      dockerfile: _dockerfiles/db/dockerfile
    env_file:
      - _dockerfiles/db/local.env
    hostname: db
    ports:
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data


volumes: 
  db-data:
    driver: local
