FROM python:3.8
ENV PYTHONUNBUFFERED 1
RUN apt update && apt install -y gettext binutils libproj-dev gdal-bin
RUN mkdir -p /code /requirements
ADD ./requirements app/requirements
RUN pip install -U pip \ 
    && pip install --no-cache-dir -r /app/requirements/base.txt \
    && pip install --no-cache-dir -r /app/requirements/develop.txt
WORKDIR /code
ADD . /code
